### ISSUE TITLE
serve randomly crashes at file save

### ISSUE THREAD

**Issue by MarcMush** [tlienart/Franklin.jl#384] opened 2020-02-26 14:28 UTC
Since Franklin v0.6 (with folder_structure v0.2), `serve` randomly crashes when I save a file (here, I changed and saved the file `edit.md`)
it only happens when saving a file, and quite rarely, which is annoying because I don't know what causes it

any ideas ?

```
┌ Error: An error happened whilst watching files; shutting down. Error was: KeyError("__site/edit/index.html")
└ @ LiveServer ~/.julia/packages/LiveServer/OCd5k/src/file_watching.jl:106
┌ Error: Exception while generating log record in module LiveServer at /home/marc/.julia/packages/LiveServer/OCd5k/src/file_watching.jl:106
│   exception =
│    InterruptException:
│    Stacktrace:
│     [1] try_yieldto(::typeof(Base.ensure_rescheduled), ::Base.RefValue{Task}) at ./task.jl:611
│     [2] wait() at ./task.jl:668
│     [3] uv_write(::Base.TTY, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:935
│     [4] unsafe_write(::Base.TTY, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:1007
│     [5] macro expansion at ./io.jl:593 [inlined]
│     [6] write(::Base.TTY, ::Array{UInt8,1}) at ./io.jl:616
│     [7] #handle_message#2(::Nothing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Base.CoreLogging.handle_message), ::Logging.ConsoleLogger, ::Base.CoreLogging.LogLevel, ::String, ::Module, ::String, ::Symbol, ::String, ::Int64) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Logging/src/ConsoleLogger.jl:161
│     [8] handle_message at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Logging/src/ConsoleLogger.jl:100 [inlined]
│     [9] macro expansion at ./logging.jl:320 [inlined]
│     [10] file_watcher_task!(::LiveServer.SimpleWatcher) at /home/marc/.julia/packages/LiveServer/OCd5k/src/file_watching.jl:106
│     [11] (::LiveServer.var"#2#3"{LiveServer.SimpleWatcher})() at ./task.jl:333
└ @ LiveServer ~/.julia/packages/LiveServer/OCd5k/src/file_watching.jl:106
```

**Comment by tlienart** [comment] 2020-02-26 15:03
Yes, sorry... this is actually not an issue with Franklin but with LiveServer, see also  https://franklinjl.org/faq/troubleshooting/ 

Unfortunately the cause of this is due to Juno / HTTP (you may be using the former and you're definitely using the latter). The former does complicated stuff and when you send an interrupt signal it may just happen to mess with it which causes the crash you're seeing. There are also issues with HTTP's server functionality which, unfortunately, doesn't always deal well with interrupt signals either.

I'm closing this  as it's not a Franklin issue.

**Closed** 2020-02-26 15:05 UTC

**Comment by tlienart** [comment] 2020-02-26 15:18
Hmm actually looking at your stacktrace there may be something that can be done... I'll investigate

**Comment by tlienart** [comment] 2020-02-26 15:46
Right, I'll do a patch release on that side with something which may help, please kindly report sometime in the near future if using LiveServer 0.3.6 (pending release) with Franklin 0.6.5 (also pending) reduces that kind of errors.

Thanks a lot!
